import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-blue-600 text-white py-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-2xl font-semibold">Frontend Craft Circle</h1>
            <nav>
              <ul className="flex space-x-6">
                <li>
                  <a href="/team" className="hover:text-gray-300">
                    Team
                  </a>
                </li>
                <li>
                  <a href="/projects" className="hover:text-gray-300">
                    Projects
                  </a>
                </li>
                <li>
                  <a href="/tech-radar" className="hover:text-gray-300">
                    Tech Radar
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main className="container mx-auto py-8"> {children} </main>
        <footer className="bg-gray-800 text-white py-4">
          <div className="container mx-auto text-center">
            <p>&copy; 2023 Company Name. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
